# Generated by Django 4.2.3 on 2023-08-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='sum_rating',
            field=models.IntegerField(default=0),
        ),
    ]
